# configs/model/stylegan2_scratch_256.yaml

# This config now has a flat structure that matches the new __init__ signatures
# in the network definitions.
_target_: src.lightning_modules.stylegan2_scratch_module.StyleGAN2ScratchLightningModule

model_cfg:
  # --- Generator Parameters ---
  z_dim: 512
  w_dim: 512
  num_mapping_layers: 8
  mapping_lr_mul: 0.01

  # --- Synthesis Network Parameters ---
  channel_base: 16384
  channel_max: 512
  resample_kernel: [1,3,3,1]

  # --- Discriminator Parameters ---
  mbstd_group_size: 4
  mbstd_num_features: 1

  # --- Shared Parameters ---
  img_resolution: 256
  img_channels: 1

  # --- Augmentation Parameters ---
  augment_pipe_kwargs:
    p_xflip: 0.5
    p_rotate90: 0.5
    p_brightness: 0.5
    p_contrast: 0.5
    brightness_range: [-0.2, 0.2]
    contrast_range: [0.8, 1.2]
