# configs/training/scratch_default_training.yaml

# --- Custom Hyperparameters for the LightningModule ---
total_kimg: 25000
# CORRECTED: Set snapshot_ticks to 1 for much more frequent image snapshots.
kimg_per_tick: 4
snapshot_ticks: 1 
nimg_snapshot: 16

g_lr: 0.0002
d_lr: 0.0001

adam_betas: [0.0, 0.99]
adam_eps: 1.0e-4 

# CORRECTED: Decreased R1 gamma to slightly weaken the discriminator.
r1_gamma: 2.0
d_reg_interval: 16
# CORRECTED: Significantly increased Path Length weight to more strongly
# regularize the generator and discourage mode collapse.
pl_weight: 10.0
g_reg_interval: 4
pl_decay: 0.01

ema_kimg: 10.0
ema_rampup_ratio: 0.05
ema_beta: 0.999
gradient_clip_val: 1.0 
ada_kwargs:
  target_rt: 0.6
  interval_kimg: 4
  speed_kimg: 500

# --- PyTorch Lightning Trainer Parameters ---
trainer:
  _target_: pytorch_lightning.Trainer
  accelerator: auto
  devices: auto
  log_every_n_steps: 2

