# configs/training/scratch_default_training.yaml

# --- Custom Hyperparameters for the LightningModule ---
total_kimg: 5000
kimg_per_tick: 4
snapshot_ticks: 1 
nimg_snapshot: 16

g_lr: 0.001
d_lr: 0.001

adam_betas: [0.0, 0.99]
adam_eps: 1.0e-8 

# CORRECTED: Added style_mixing_prob to enable the new regularization.
# This is the final step in fixing the mode collapse issue.
style_mixing_prob: 0.9

r1_gamma: 50.0
d_reg_interval: 16
pl_weight: 2.0
g_reg_interval: 4
pl_decay: 0.01

ema_kimg: 10.0
ema_rampup_ratio: 0.05
ema_beta: 0.999
gradient_clip_val: 1.0 
ada_kwargs:
  target_rt: 0.8
  interval_kimg: 4
  speed_kimg: 500

# --- PyTorch Lightning Trainer Parameters ---
trainer:
  _target_: pytorch_lightning.Trainer
  accelerator: auto
  devices: auto
  log_every_n_steps: 2

