# configs/main_config.yaml

# This is the main configuration file for the project.

# --- Project Settings ---
project_name: "cars_gen_advanced"
seed: 42
project_root: "."
tags: ["stylegan2_scratch", "cars_thyroid", "initial_from_scratch_run"]
notes: "Initial from-scratch StyleGAN2 implementation for CARS thyroid dataset."

# --- Default Configurations ---
defaults:
  # CORRECTED: Added '_self_' to follow Hydra 1.1+ best practices
  # and resolve the UserWarning.
  - _self_
  - data: cars_stylegan_data_default.yaml
  - model: stylegan2_scratch_256.yaml
  - training: scratch_default_training.yaml
  - evaluation: default_evaluation.yaml
  - override hydra/job_logging: default
  - override hydra/hydra_logging: default

# --- PyTorch Lightning Logger Configuration ---
logger:
  _target_: pytorch_lightning.loggers.TensorBoardLogger
  save_dir: "${hydra:run.dir}"
  name: ""
  version: ""

# --- Hydra Configuration ---
hydra:
  run:
    dir: ${project_root}/outputs/${project_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${project_root}/outputs/${project_name}/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}

