# configs/main_config.yaml

# This is the main configuration file for the project.

# --- Project Settings ---
project_name: "cars_gen_advanced"
seed: 42
project_root: "." # Using Hydra's variable for project root is a good practice.
tags: ["stylegan2_scratch", "cars_thyroid", "initial_from_scratch_run"]
notes: "Initial from-scratch StyleGAN2 implementation for CARS thyroid dataset."
outputs_dir: outputs

# --- Default Configurations ---
defaults:
  - data: cars_stylegan_data_default.yaml
  - model: stylegan2_scratch_256.yaml
  - training: scratch_default_training.yaml
  - evaluation: default_evaluation.yaml
  # CORRECTED: Reverted to the standard 'default' logger which is always available.
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

# --- PyTorch Lightning Logger Configuration ---
# This configuration tells the logger to save its files directly into the
# output directory that Hydra creates, preventing nested folders.
training: # This allows overriding or extending the training config from cvae_trainer_for_ldm.yaml
  logger:
    _target_: pytorch_lightning.loggers.TensorBoardLogger
    save_dir: "${hydra:runtime.output_dir}/tb_logs" # Save TB logs within the Hydra run directory
    name: "${model.model_name}" # Group logs by model name
    version: "" # No specific version subdirectory, logs directly under model_name

